PTEUDO1064 - Create users, schemas, roles and rotate password
infobloxopen/db-controller pull request #250
Opened 2024-07-05 20:44 UTC by EvertonCalgarotto

Update DBRoleClaim to hold new properties regarding user, schemas and roles to create.

Write unit tests.

2024-07-05 21:40 UTC, drewwells commented on README.md
> +Otherwise it'll run against an old version (see next step)
The integration tests install into the cluster now using `make deploy`

2024-07-05 21:41 UTC, drewwells commented on README.md
> +2. Update file dbc_end2end_test.go (line 56) and file '.id' in the root folder, with a class name of your own (let's say your username). That will be used to create a namespace and the CRDs under it.
Integration tests use `make` so class name is discovered automatically now.

2024-07-05 21:43 UTC, drewwells commented on README.md
> +4. in case the tests failed in the middle, sometimes the resources are not deleted from the AWS account. So you can go in there and delete the RDSs that were created. They can be searched for by usin
We should make sure integration tests provision crossplane CRs that when deleted also delete the AWS resources. They probably preserve databases right now

2024-07-05 21:44 UTC, drewwells commented on config/crd/bases/persistance.atlas.infoblox.com_dbroleclaims.yaml
> +                type: string
This should be optional. We don't want anybody picking their usernames. We can do something like
`{basename}_{dbroleclaimname}_[a|b]`

2024-07-05 22:12 UTC, drewwells requested changes
Field Indexer is the big miss. The rest is more like nits on the code

2024-07-05 22:12 UTC, drewwells commented on pkg/dbclient/client.go
> +			return created, err
```suggestion
			return false, fmt.Errorf("connect_db %s: %w", dbName, err)
```

2024-07-05 22:12 UTC, drewwells commented on pkg/dbclient/client.go
> +			return created, err
```suggestion
			metrics.UsersCreatedErrors.WithLabelValues("grant_error").Inc()
			return false, fmt.Errorf("grant_schema_privileges %s: %w", dbName, err)
```

2024-07-05 22:12 UTC, drewwells commented on pkg/dbclient/client_test.go
> +// }
Can these tests be uncommented?

2024-07-05 22:12 UTC, drewwells commented on pkg/dbclient/interface.go
> +	AssignRoleToUser(username, rolename string) error
Consider breaking out this into a separate interface. It's very hard to mock and write tests with interfaces that implement dozen+ methods. However, you can easily pass around an object that implements multiple interfaces.

Can you also rename this interface to `Clienter`

Creater // CreateDatabase, CreateUser, CreateSchema
Exister // SchemaExists, ... 

It's fine for Clienter to implement all of the individual interfaces
```
type Clienter interface {
  Creater
  Exister
```

2024-07-05 22:12 UTC, drewwells commented on pkg/dbclient/testdb.go
> +func (t *testDB) Close() {
```suggestion
func (t *testDB) Close() {
  t.Helper()
```

2024-07-05 22:12 UTC, drewwells commented on pkg/dbclient/testdb.go
> +func (t *testDB) Close() {
Add t.Helper() on all of these helper methods

2024-07-05 22:12 UTC, drewwells commented on pkg/dbuser/dbuser.go
> +	if strings.HasSuffix(curUser, SuffixA) {
`NextUser()` logic tends to be more sophisticated than this. What if a completely incorrect username comes in? Maybe this needs an error and some sanity checks, especially if you're going to drop the checking on db.userA entirely here.

2024-07-05 22:12 UTC, drewwells commented on pkg/roleclaim/roleclaim.go
> +	_ "github.com/lib/pq"
```suggestion
	"github.com/lib/pq"
```

2024-07-05 22:12 UTC, drewwells commented on pkg/roleclaim/roleclaim.go
> +func (r *DbRoleClaimReconciler) copySourceSecret(ctx context.Context, sourceSecret *corev1.Secret, dbRoleClaim *v1.DbRoleClaim, newUser, newPassword string) error {
Are you leaving the copySourceSecret logic as is, or upgrading them to use separate username/password combinations?

2024-07-08 16:09 UTC, EvertonCalgarotto commented on README.md
> +Otherwise it'll run against an old version (see next step)
ok, change to this then:

`1. Integration tests run against server box-3. Before running your tests, you'll have to build and deploy to make sure you are running against the latest version.

2. Update file '.id' in the root folder, with a class name of your own (let's say your username). That will be used to create a namespace and the CRDs under it.
Then run:
    make docker-build
    make deploy`

2024-07-08 16:11 UTC, EvertonCalgarotto commented on README.md
> +4. in case the tests failed in the middle, sometimes the resources are not deleted from the AWS account. So you can go in there and delete the RDSs that were created. They can be searched for by usin
included this piece here, cause resources are deleted, it's just that they might take a long time.

`(actually it might takes a long time sometimes).`

2024-07-08 16:18 UTC, EvertonCalgarotto commented on config/crd/bases/persistance.atlas.infoblox.com_dbroleclaims.yaml
> +                type: string
You mean make it optional or remove it entirely?
I guess it is better to have this property instead of using a built up name like the one you are proposing, cause a "username" property makes it easier for the consumer of the DBController (the app teams) what to expect when using the connstring and also, it's easier for them to create the DBRole request. They won't have to think what the username will be.

2024-07-08 16:19 UTC, EvertonCalgarotto commented on internal/controller/dbroleclaim_controller.go
> +// // SetupWithManager sets up the controller with the Manager.
removed.

2024-07-08 16:26 UTC, EvertonCalgarotto commented on internal/controller/dbroleclaim_controller.go
> -	}
put it back

2024-07-08 16:29 UTC, EvertonCalgarotto commented on pkg/dbclient/client.go
> +		url.QueryEscape(user), url.QueryEscape(password), host, port, url.QueryEscape(dbname), sslmode)
Sure, no reason to have it as paremeter.

2024-07-08 16:36 UTC, EvertonCalgarotto commented on pkg/dbclient/interface.go
> +	AssignRoleToUser(username, rolename string) error
Good point. Created interfaces 
Creater
Exister
Updater

2024-07-08 16:43 UTC, EvertonCalgarotto commented on README.md
> +2. Update file dbc_end2end_test.go (line 56) and file '.id' in the root folder, with a class name of your own (let's say your username). That will be used to create a namespace and the CRDs under it.
updated

2024-07-08 16:54 UTC, EvertonCalgarotto commented on pkg/roleclaim/roleclaim.go
> +func (r *DbRoleClaimReconciler) copySourceSecret(ctx context.Context, sourceSecret *corev1.Secret, dbRoleClaim *v1.DbRoleClaim, newUser, newPassword string) error {
As is, cause if no username is provided, it means we want the normal behavior of the DBRoleClaim, that is just to copy the secret under a different name.

2024-07-08 17:18 UTC, EvertonCalgarotto commented on pkg/dbuser/dbuser.go
> +	if strings.HasSuffix(curUser, SuffixA) {
I put a verification in the roleclaim controller to validate the format of the username, so we don't get weird names

2024-07-08 18:51 UTC, EvertonCalgarotto commented on config/crd/bases/persistance.atlas.infoblox.com_dbroleclaims.yaml
> +                type: string
ok, we talked about it in slack. I'll remove this property and use <dbclaimrolename>_user_[a|b]

2024-07-08 20:20 UTC, drewwells commented on pkg/basefunctions/basefunctions.go
> +)
Not a big fan of generic packages with names that don't indicate intent. https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common
A lot of this behavior is only applicable to one other package too. Probably better to keep it closer to that controller.

2024-07-08 20:26 UTC, drewwells commented on pkg/basefunctions/basefunctions.go
> +)
Another article on the topic https://google.github.io/styleguide/go/best-practices.html#util-packages

2024-07-08 20:46 UTC, drewwells approved these changes

2024-07-08 20:49 UTC, EvertonCalgarotto commented on pkg/basefunctions/basefunctions.go
> +)
I thought of this because these values are used in multiple places. I could instead have created a class under "pkg" folder but it doesn't look right to the structure.

2024-07-08 21:34 UTC, merged