Pteudo 1247
infobloxopen/db-controller pull request #286
Opened 2024-08-26 17:40 UTC by leandrorichardtoledo

- It addresses the ticket: [PTEUDO-1247](https://infoblox.atlassian.net/browse/PTEUDO-1247);
- Removed input and mode global vars from the reconciler struct;
- Refactored code for passing the request info and mode when needed;

2024-08-26 17:52 UTC, EvertonCalgarotto approved these changes
Looks good!

2024-08-26 19:44 UTC, drewwells requested changes
Some unit tests on this would be helpful to verify functionality. Made some comments to remove this from the reconciler struct so it can run independently

2024-08-26 19:44 UTC, drewwells commented on pkg/databaseclaim/databaseclaim.go
> +func (r *DatabaseClaimReconciler) getDynamicHostName(hash string, dbClaim *v1.DatabaseClaim) string {
Remove this from the reconciler object. Pass in the 'dbidentifierprefix' which is just the env name. Feel free to just rename it to envname as well.

2024-08-26 19:44 UTC, drewwells commented on pkg/databaseclaim/requestinfo.go
> +func (r *DatabaseClaimReconciler) setRequestInfo(dbClaim *v1.DatabaseClaim) (requestInfo, error) {
The goal is to split all of this code up into smaller pieces. To get there, this should not hang off the reconciler struct and make a bunch of calls into the reconciler to find things. 

Change this to receive the Config and dbClaim as parameters. Made some comments above on getDynamicHostName to remove that dependence on reconciler struct too.
```suggestion
func NewRequestInfo(config *DatabaseClaimConfig, dbClaim *v1.DatabaseClaim) (requestInfo, error) {
```

2024-09-09 16:18 UTC, drewwells commented on pkg/databaseclaim/requestinfo.go
> +func (r *DatabaseClaimReconciler) setRequestInfo(dbClaim *v1.DatabaseClaim) (requestInfo, error) {
pass in the viper config and things to call `r.getDynamicHostName(hostParams.Hash(), dbClaim)`, so the reconciler method receiver can be removed.
`NewRequestInfo(dbClaim *v1.DatabaseClaim, ViperConfig...)`

2024-09-09 16:19 UTC, drewwells commented on pkg/databaseclaim/requestinfo.go
> +	enableCloudwatchLogsExport := basefun.GetEnableCloudwatchLogsExport(r.Config.Viper)
This is a great reason to stop passing around viperconfig, it makes calling basefun methods very difficult. We should just have a config package to find these configuration parameters, then we could just do
```
backupRetentionDays = config.BackupRetentionDays
caCertificateIdentifier = config.CACertificateIdentifier
... etc
```

2024-09-16 20:06 UTC, drewwells approved these changes

2024-09-16 20:11 UTC, merged