Updated docs with proposed design.
infobloxopen/db-controller pull request #31
Opened 2022-04-11 21:46 UTC by seizadi

In the case of authSource for db-controller I document existing design.

2022-04-11 22:25 UTC, daniel-garcia requested changes

2022-04-11 22:25 UTC, daniel-garcia commented on docs/index.md
> +      - RAM: The optional RAM value requests the database host memory capacity
Lets not expose RAM or CPU options to end users. They pick a shape.. nothing else.

2022-04-11 22:25 UTC, daniel-garcia commented on docs/index.md
> +      - Storage: The optional Storage value requests the database host storage capacity
This should be min-storage. The controller may over provision storage and thats ok.

2022-04-11 22:25 UTC, daniel-garcia commented on docs/index.md
> +* authSource: Determines how database host master password is retrieved. The possible values are "secret" and "aws". In the case of "secret" the value from the passwordSecretRef Secret is used for th
this is something the controller should decide based on its configuration

2022-04-11 22:38 UTC, seizadi commented on docs/index.md
> +* authSource: Determines how database host master password is retrieved. The possible values are "secret" and "aws". In the case of "secret" the value from the passwordSecretRef Secret is used for th
I am just documenting current implementation here. The new design will not use this pattern, as it is part of infrastructure concern.

2022-04-11 22:38 UTC, seizadi commented on docs/index.md
> +      - Storage: The optional Storage value requests the database host storage capacity
OK

2022-04-11 22:38 UTC, seizadi commented on docs/index.md
> +      - RAM: The optional RAM value requests the database host memory capacity
OK

2022-04-12 00:54 UTC, daniel-garcia approved these changes

2022-06-07 21:36 UTC, daniel-garcia approved these changes

2022-06-07 21:36 UTC, merged