Use the TAG being built in db-controller chart values
infobloxopen/db-controller pull request #65
Opened 2022-07-18 22:18 UTC by cxvisa

2022-07-18 22:35 UTC, daniel-garcia requested changes

2022-07-18 22:35 UTC, daniel-garcia commented on Makefile
> +	sed -i "/  tag: \"latest\"/c\  tag: ${TAG}" ${DB_CONTROLLER_CHART_VALUES}
doing this inline will lead to someone checking in the actual tag then this won't work anymore. I suggest using a .in file or following appVersion see
https://stackoverflow.com/questions/58065225/image-tag-in-values-yaml-vs-appversion-in-chart-yaml

2022-07-18 22:51 UTC, cxvisa commented on Makefile
> +	sed -i "/  tag: \"latest\"/c\  tag: ${TAG}" ${DB_CONTROLLER_CHART_VALUES}
remove the values.yaml file from git and have values.in file that generates the values.yaml file?  Did I understand it right?

2022-07-19 16:11 UTC, cxvisa commented on Makefile
> +	sed -i "/  tag: \"latest\"/c\  tag: ${TAG}" ${DB_CONTROLLER_CHART_VALUES}
Added values.in file and removed values.yaml file from the git repo.  Now the values.yaml file gets generated on the fly.  We now set AppVersion in the Chart during package time (it is set to the TAG computed).  The deployment image version is picked from .Values.image.tag and if it is not set default value is set to.Chart.AppVersion.

2022-07-19 17:24 UTC, daniel-garcia approved these changes
LGTM

2022-07-19 17:27 UTC, merged